-- Migration: 0001_initial_triggers.sql
-- Loyola Digital X — Triggers and functions (manual, not generated by Drizzle)
-- Run AFTER drizzle-kit migrate applies the schema

BEGIN;

-- ============================================================
-- FUNCTIONS & TRIGGERS
-- ============================================================

-- Auto-update updated_at on row modification
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_users_updated_at
  BEFORE UPDATE ON users
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

CREATE TRIGGER trg_conversations_updated_at
  BEFORE UPDATE ON conversations
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

CREATE TRIGGER trg_delegated_tasks_updated_at
  BEFORE UPDATE ON delegated_tasks
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();


-- Auto-update conversation counters when message inserted
CREATE OR REPLACE FUNCTION update_conversation_counters()
RETURNS TRIGGER AS $$
BEGIN
  UPDATE conversations SET
    message_count = message_count + 1,
    total_tokens = total_tokens + COALESCE(NEW.tokens_used, 0),
    updated_at = now()
  WHERE id = NEW.conversation_id;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_messages_update_counters
  AFTER INSERT ON messages
  FOR EACH ROW EXECUTE FUNCTION update_conversation_counters();


-- Auto-generate conversation title from first user message
CREATE OR REPLACE FUNCTION auto_title_conversation()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.role = 'user' THEN
    UPDATE conversations SET
      title = left(NEW.content, 80)
    WHERE id = NEW.conversation_id
      AND title IS NULL;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_messages_auto_title
  AFTER INSERT ON messages
  FOR EACH ROW EXECUTE FUNCTION auto_title_conversation();

COMMIT;
